<a href="https://colab.research.google.com/github/susan-awori/Data-processing/blob/main/Data_pre_processing_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

df = pd.read_csv('STEG_BILLING_HISTORY.csv')
client_0_bills = df.head(10)
client_0_bills

,client_id,invoice_date,tarif_type,counter_number,counter_statue,counter_code,reading_remarque,counter_coefficient,consommation_level_1,consommation_level_2,consommation_level_3,consommation_level_4,old_index,new_index,months_number,counter_type
0,train_Client_0,2014-03-24,11.0,1335667.0,0.0,203.0,8.0,1.0,82.0,0.0,0.0,0.0,14302.0,14384.0,4.0,ELEC
1,train_Client_0,2013-03-29,11.0,1335667.0,0.0,203.0,6.0,1.0,1200.0,184.0,0.0,0.0,12294.0,13678.0,4.0,ELEC
2,train_Client_0,2015-03-23,11.0,1335667.0,0.0,203.0,8.0,1.0,123.0,0.0,0.0,0.0,14624.0,14747.0,4.0,ELEC
3,train_Client_0,2015-07-13,11.0,1335667.0,0.0,207.0,8.0,1.0,102.0,0.0,0.0,0.0,14747.0,14849.0,4.0,ELEC
4,train_Client_0,2016-11-17,11.0,1335667.0,0.0,207.0,9.0,1.0,572.0,0.0,0.0,0.0,15066.0,15638.0,12.0,ELEC
5,train_Client_0,2017-07-17,11.0,1335667.0,0.0,207.0,9.0,1.0,314.0,0.0,0.0,0.0,15638.0,15952.0,8.0,ELEC
6,train_Client_0,2018-12-07,11.0,1335667.0,0.0,207.0,9.0,1.0,541.0,0.0,0.0,0.0,15952.0,16493.0,12.0,ELEC
7,train_Client_0,2019-03-19,11.0,1335667.0,0.0,207.0,9.0,1.0,585.0,0.0,0.0,0.0,16493.0,17078.0,8.0,ELEC
8,train_Client_0,2011-07-22,11.0,1335667.0,0.0,203.0,9.0,1.0,1200.0,186.0,0.0,0.0,7770.0,9156.0,4.0,ELEC
9,train_Client_0,2011-11-22,11.0,1335667.0,0.0,203.0,6.0,1.0,1082.0,0.0,0.0,0.0,9156.0,10238.0,4.0,ELEC

In [ ]:
type(client_0_bills)

pandas.core.frame.DataFrame

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 759442 entries, 0 to 759441
Data columns (total 16 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   client_id             759442 non-null  object
 1   invoice_date          759442 non-null  object
 2   tarif_type            759441 non-null  float64
 3   counter_number        759434 non-null  float64
 4   counter_statue        759441 non-null  float64
 5   counter_code          759441 non-null  float64
 6   reading_remarque      758675 non-null  float64
 7   counter_coefficient   759441 non-null  float64
 8   consommation_level_1  759441 non-null  float64
 9   consommation_level_2  759441 non-null  float64
 10  consommation_level_3  759441 non-null  float64
 11  consommation_level_4  759441 non-null  float64
 12  old_index             759441 non-null  float64
 13  new_index             759441 non-null  float64
 14  months_number         759441 non-null  float64
 15  counter_type          759441 non-null  object
dtypes: float64(13), object(3)
memory usage: 92.7+ MB

In [ ]:
df.memory_usage(deep=True).sum()

np.int64(215359895)

How many rows and columns:
How many categorical features: 2
How much memory: 92.7+ MB

In [ ]:
df.select_dtypes(include='object').shape[1]

3

In [ ]:
df.isnull().sum()

client_id                 0
invoice_date              0
tarif_type                1
counter_number            8
counter_statue            1
counter_code              1
reading_remarque        767
counter_coefficient       1
consommation_level_1      1
consommation_level_2      1
consommation_level_3      1
consommation_level_4      1
old_index                 1
new_index                 1
months_number             1
counter_type              1
dtype: int64

In [ ]:
df[df['tarif_type'].isnull()]

,client_id,invoice_date,tarif_type,counter_number,counter_statue,counter_code,reading_remarque,counter_coefficient,consommation_level_1,consommation_level_2,consommation_level_3,consommation_level_4,old_index,new_index,months_number,counter_type
759441,train_Client_120521,2009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df = df.dropna(subset=['tarif_type'])

I chose this bcs If a whole bill is blank, there's nothing useful to learn from it. Throwing away 1 page from a huge notebook doesn't change the story, and guessing numbers for a page with no information would be making things up.

In [ ]:
df = df.dropna(subset=['counter_number'])

Here a A counter number is like a name tag, not a measurement. I can't use the average name tag to fill it in, because it would be pretend information. Only 8 rows are affected, so losing them is cheap.

In [ ]:
df['reading_remarque'] = df['reading_remarque'].fillna(-1)

In [ ]:
df.isnull().sum()

client_id               0
invoice_date            0
tarif_type              0
counter_number          0
counter_statue          0
counter_code            0
reading_remarque        0
counter_coefficient     0
consommation_level_1    0
consommation_level_2    0
consommation_level_3    0
consommation_level_4    0
old_index               0
new_index               0
months_number           0
counter_type            0
dtype: int64

In [ ]:
df.describe()

,tarif_type,counter_number,counter_statue,counter_code,reading_remarque,counter_coefficient,consommation_level_1,consommation_level_2,consommation_level_3,consommation_level_4,old_index,new_index,months_number
count,759434.000000,7.594340e+05,759434.000000,759434.000000,759434.000000,759434.000000,759434.000000,759434.000000,759434.000000,759434.000000,7.594340e+05,7.594340e+05,759434.000000
mean,20.140434,1.170725e+11,0.042204,171.989777,7.312425,1.000313,408.735997,108.513323,20.635938,52.150249,1.758357e+04,1.815480e+04,36.165852
std,13.479132,1.618180e+12,0.374672,133.383590,1.385633,0.097531,575.029255,1293.741942,175.398664,976.194924,4.010562e+04,4.067677e+04,2122.888258
min,8.000000,0.000000e+00,0.000000,5.000000,-1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,1.000000
25%,11.000000,1.227460e+05,0.000000,5.000000,6.000000,1.000000,79.000000,0.000000,0.000000,0.000000,1.778000e+03,2.048000e+03,4.000000
50%,11.000000,4.931600e+05,0.000000,203.000000,8.000000,1.000000,272.000000,0.000000,0.000000,0.000000,7.642000e+03,8.143000e+03,4.000000
75%,40.000000,1.112725e+06,0.000000,207.000000,9.000000,1.000000,601.000000,0.000000,0.000000,0.000000,2.173000e+04,2.242100e+04,4.000000
max,45.000000,2.738110e+13,5.000000,600.000000,9.000000,50.000000,93385.000000,819886.000000,45360.000000,343568.000000,2.800280e+06,2.870972e+06,285398.000000

In [ ]:
df.loc[df['client_id'] == 'train_Client_0']

,client_id,invoice_date,tarif_type,counter_number,counter_statue,counter_code,reading_remarque,counter_coefficient,consommation_level_1,consommation_level_2,consommation_level_3,consommation_level_4,old_index,new_index,months_number,counter_type
0,train_Client_0,2014-03-24,11.0,1335667.0,0.0,203.0,8.0,1.0,82.0,0.0,0.0,0.0,14302.0,14384.0,4.0,ELEC
1,train_Client_0,2013-03-29,11.0,1335667.0,0.0,203.0,6.0,1.0,1200.0,184.0,0.0,0.0,12294.0,13678.0,4.0,ELEC
2,train_Client_0,2015-03-23,11.0,1335667.0,0.0,203.0,8.0,1.0,123.0,0.0,0.0,0.0,14624.0,14747.0,4.0,ELEC
3,train_Client_0,2015-07-13,11.0,1335667.0,0.0,207.0,8.0,1.0,102.0,0.0,0.0,0.0,14747.0,14849.0,4.0,ELEC
4,train_Client_0,2016-11-17,11.0,1335667.0,0.0,207.0,9.0,1.0,572.0,0.0,0.0,0.0,15066.0,15638.0,12.0,ELEC
5,train_Client_0,2017-07-17,11.0,1335667.0,0.0,207.0,9.0,1.0,314.0,0.0,0.0,0.0,15638.0,15952.0,8.0,ELEC
6,train_Client_0,2018-12-07,11.0,1335667.0,0.0,207.0,9.0,1.0,541.0,0.0,0.0,0.0,15952.0,16493.0,12.0,ELEC
7,train_Client_0,2019-03-19,11.0,1335667.0,0.0,207.0,9.0,1.0,585.0,0.0,0.0,0.0,16493.0,17078.0,8.0,ELEC
8,train_Client_0,2011-07-22,11.0,1335667.0,0.0,203.0,9.0,1.0,1200.0,186.0,0.0,0.0,7770.0,9156.0,4.0,ELEC
9,train_Client_0,2011-11-22,11.0,1335667.0,0.0,203.0,6.0,1.0,1082.0,0.0,0.0,0.0,9156.0,10238.0,4.0,ELEC
10,train_Client_0,2008-11-25,11.0,1335667.0,0.0,203.0,6.0,1.0,174.0,0.0,0.0,0.0,5417.0,5591.0,4.0,ELEC
11,train_Client_0,2012-07-23,11.0,1335667.0,0.0,203.0,6.0,1.0,628.0,0.0,0.0,0.0,10780.0,11408.0,4.0,ELEC
12,train_Client_0,2012-11-29,11.0,1335667.0,0.0,203.0,6.0,1.0,886.0,0.0,0.0,0.0,11408.0,12294.0,4.0,ELEC
13,train_Client_0,2013-07-22,11.0,1335667.0,0.0,203.0,8.0,1.0,147.0,0.0,0.0,0.0,13983.0,14130.0,4.0,ELEC
14,train_Client_0,2014-07-18,11.0,1335667.0,0.0,203.0,8.0,1.0,99.0,0.0,0.0,0.0,14384.0,14483.0,4.0,ELEC
15,train_Client_0,2014-11-24,11.0,1335667.0,0.0,203.0,8.0,1.0,141.0,0.0,0.0,0.0,14483.0,14624.0,4.0,ELEC
16,train_Client_0,2015-11-18,11.0,1335667.0,0.0,207.0,9.0,1.0,217.0,0.0,0.0,0.0,14849.0,15066.0,4.0,ELEC
17,train_Client_0,2012-03-27,11.0,1335667.0,0.0,203.0,8.0,1.0,292.0,0.0,0.0,0.0,10488.0,10780.0,4.0,ELEC
18,train_Client_0,2011-03-30,11.0,1335667.0,0.0,203.0,6.0,1.0,497.0,0.0,0.0,0.0,7273.0,7770.0,4.0,ELEC
19,train_Client_0,2013-02-12,11.0,1335667.0,0.0,203.0,8.0,1.0,38.0,0.0,0.0,0.0,14264.0,14302.0,2.0,ELEC
20,train_Client_0,2010-07-22,11.0,1335667.0,0.0,203.0,6.0,1.0,278.0,0.0,0.0,0.0,6761.0,7039.0,4.0,ELEC
21,train_Client_0,2010-11-24,11.0,1335667.0,0.0,203.0,6.0,1.0,234.0,0.0,0.0,0.0,7039.0,7273.0,4.0,ELEC
22,train_Client_0,2005-10-17,11.0,1335667.0,0.0,203.0,6.0,1.0,124.0,0.0,0.0,0.0,3685.0,3809.0,4.0,ELEC
23,train_Client_0,2006-02-24,11.0,1335667.0,0.0,203.0,6.0,1.0,141.0,0.0,0.0,0.0,3809.0,3950.0,4.0,ELEC
24,train_Client_0,2006-06-23,11.0,1335667.0,0.0,203.0,6.0,1.0,162.0,0.0,0.0,0.0,3950.0,4112.0,4.0,ELEC
25,train_Client_0,2006-10-18,11.0,1335667.0,0.0,203.0,6.0,1.0,159.0,0.0,0.0,0.0,4112.0,4271.0,4.0,ELEC
26,train_Client_0,2007-06-27,11.0,1335667.0,0.0,203.0,6.0,1.0,240.0,0.0,0.0,0.0,4453.0,4693.0,4.0,ELEC
27,train_Client_0,2007-10-25,11.0,1335667.0,0.0,203.0,6.0,1.0,276.0,0.0,0.0,0.0,4693.0,4969.0,4.0,ELEC
28,train_Client_0,2007-02-26,11.0,1335667.0,0.0,203.0,6.0,1.0,182.0,0.0,0.0,0.0,4271.0,4453.0,4.0,ELEC
29,train_Client_0,2008-07-28,11.0,1335667.0,0.0,203.0,6.0,1.0,171.0,0.0,0.0,0.0,5246.0,5417.0,4.0,ELEC
30,train_Client_0,2009-01-04,11.0,1335667.0,0.0,203.0,6.0,1.0,315.0,0.0,0.0,0.0,5591.0,5906.0,4.0,ELEC
31,train_Client_0,2009-07-27,11.0,1335667.0,0.0,203.0,6.0,1.0,312.0,0.0,0.0,0.0,5906.0,6218.0,4.0,ELEC
32,train_Client_0,2009-11-24,11.0,1335667.0,0.0,203.0,6.0,1.0,267.0,0.0,0.0,0.0,6218.0,6485.0,4.0,ELEC
33,train_Client_0,2010-03-29,11.0,1335667.0,0.0,203.0,6.0,1.0,276.0,0.0,0.0,0.0,6485.0,6761.0,4.0,ELEC
34,train_Client_0,2008-01-04,11.0,1335667.0,0.0,203.0,6.0,1.0,277.0,0.0,0.0,0.0,4969.0,5246.0,4.0,ELEC

In [ ]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
df['counter_type'] = encoder.fit_transform(df['counter_type'])

In [ ]:
df = df.drop('counter_statue', axis=1)